### ISSUE TITLE
Handle different/multiple trace context propagation headers

### ISSUE THREAD

**Issue by chingor13** [census-instrumentation/opencensus-ruby#29]
We're currently relying on the `Trace-Context` header but this needs to be customizable. If the user wants to use the `CloudTrace` formatter, then the header should be `X-Cloud-Trace`.

**Comment by chingor13** [comment]
I see a couple of options here:

1. Add a `header_name` option to relevant methods (`SpanContext.create_root`, `FaradayMiddleware#initialize`)
2. Add a `header_name` attribute to the formatter duck types
3. Introduce a propagator duck type that has a formatter and a header name. Replace the formatter options with propagator option.

**Comment by dazuma** [comment]
Since header name and format are coupled, seems like they should be part of the same duck type. That said, I'm trying to figure out what that interface should look like and how it should be used. Formatter doesn't belong as a field on SpanContext (as it currently is) because SpanContext should not be concerned with how stuff gets propagated—that decision should be deferred to the integration (e.g. faraday or grpc) charged with implementing it. Indeed, the only real decision/configuration that can be made here is with outgoing http requests (i.e. the faraday integration), which header to send out, or even whether to send both headers. So maybe you don't need a duck type at all. Formatters are just helper classes. SpanContext checks all possible incoming headers (maybe the priority order is customizable) and sets trace context from whatever it finds. Then the outgoing integrations are responsible to use whatever formatter(s) are relevant to them.
