### ISSUE TITLE
Integration with libraries that don't support instrumentation

### ISSUE THREAD

**Issue by nguyenquangminh0711** [census-instrumentation/opencensus-ruby#43]
Hi opencensus-ruby,

The opencensus project has just been open sourced and it looks promising. At the moment, it lacks the integrations with core Ruby standard libraries like net/http, net/https and many common libraries in Ruby ecosystems like Redis, HTTParty, Dalli, Kafka, etc. I would like to give a hand on the project to implement those integrations. However, at the first glance at the codebase, it looks like the opencensus-ruby team favors the use of middlewares and instrumentations. In many Ruby libraries, the support of instrumentations is limited or even non-existing. The only solutions to integrate into them is to monkey-patch into the library core like many other APM libraries are doing. I would like to know whether this is an acceptable solution for the integration? If not, please point out the favored approach for the project so that others could follow.

Look forward to your responses soon. I'm so excited about the library.

**Comment by nguyenquangminh0711** [comment]
Based on the specification in https://github.com/census-instrumentation/opencensus-specs, it looks like we could use monkey-patch method for Ruby library? 
cc @dazuma @chingor13

**Comment by dazuma** [comment]
Monkey-patching is generally not the preferred method of integration, but it is sometimes unavoidable. So yes, we do expect monkey patches to be used sometimes, if alternate hooks are not available for the library you're instrumenting.

If you do end up monkey-patching, please follow good practices to give the best chance for forward compatibility. For example, try to patch public methods rather than internal methods; if possible wrap a method (i.e. call the original from the patch) rather than replace the method; and otherwise minimize assumptions you make about the library's implementation. If you're uncertain, feel free to post your ideas here, and we can discuss them.

**Comment by dazuma** [comment]
Another important design principle we're adhering to. Generally, integrations should be opt-in. An application should have to require a particular file, or call some method, to install an integration. (For example, an application should have to explicitly install a middleware, or call a `patch_net_http` method.) Don't automatically patch something for all applications without asking the application first. We're prioritizing compatibility and explicitness over magic.

**Comment by dazuma** [comment]
I'm closing this. Please feel free to reach out again if you have further questions.
